#!/bin/bash
# (C) 2020 Benjamin Steenkamer.
# Combine multiple .pdf files into a single .pdf.
# Usage: ./pdfcombine.sh input1.pdf input2.pdf...

pdftk "$@" cat output output.pdf verbose    # "$@" expands to separate words: "$1" "$2" ...
